#green
version: '3'
services:
    nextjs: 
        build:
            context: /home/ec2-user/next-tutorial
            dockerfile: ./deploy/Dockerfile
        restart: unless-stopped
        ports:
            - 3002:3000