#green
version: '3'
services:
    nginx:
        build: 
            context: /home/ec2-user/next-tutorial
            dockerfile: ./nginx/Dockerfile
        restart: unless-stopped
        ports:
            - 80:80